### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CHparis** [donghao1393/mcp-dbutils#110]
## 问题描述
docker pull mcp/dbutils的时候，Error response from daemon: pull access denied for mcp/dbutils, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

## 复现步骤
docker pull mcp/dbutils无法pull成功

## 截图

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/356827e9-d805-417b-bdbc-a49b6cfb085f" />

## 环境信息

- MCP数据库工具版本: 1.0.3
- 操作系统: Mac os
- Python版本: 3.13
- 数据库类型和版本:SQLite 3.39.0
- 使用的MCP客户端: 自定义

## 配置文件

```yaml
connections:
  example_connection:
    type: sqlite
    path: ":memory:"
```
