### ISSUE TITLE
[Bug] 在Docker容器中使用离线安装的方式出下如下异常

### ISSUE THREAD

**Issue by CHparis** [donghao1393/mcp-dbutils#112]
## Description
在使用docker容器的时候，通过源码安装的方式进行安装的时候，会出下如下error

<img width="837" alt="Image" src="https://github.com/user-attachments/assets/68fe22b5-2043-41a5-9876-178c5dde3643" />

## Environment

- MCP Database Utilities version: [e.g. 0.19.0]
- OS: [e.g. Windows 10, macOS 12.0, Ubuntu 22.04]
- Python version: [e.g. 3.10.5]
- Database type and version: [e.g. SQLite 3.39.0, PostgreSQL 14.5, MySQL 8.0.30]
- MCP client used: [e.g. Claude Desktop, VS Code, Cursor]

## Configuration

```yaml
connections:
  example_connection:
    type: sqlite
    path: ":memory:"
```
